name: build-workshop-page

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.10.15
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.15

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # Build the page
    - name: Build the workshop page
      run: |
        jupyter-book build workshop/
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./workshop/_build/html